import { FileImage, QrCode, Timer, Receipt, RefreshCw, Keyboard, Grid3X3, Crop, Eraser, Sparkles, FileText, Combine, Split, Minimize2, ImagePlus, NotebookPen, FileEdit, Hash, Table, WholeWord, Gamepad2, Calculator, PenTool, CreditCard, Palette, Shapes, Images, KanbanSquare, CropIcon, ScanLine, Crown, Unlock } from "lucide-react";

export type ToolCategory = "Images" | "Generate" | "Productivity" | "Business" | "PDF" | "Games" | "Design Training";

export interface Tool {
    id: string;
    name: string;
    description: string;
    href: string;
    badge: "Free";
    icon: any; // Lucide icon
    tags: string[];
    accent: string;
    category: ToolCategory;
}

export const ALL_TOOLS: Tool[] = [
    {
        id: "pdf-signer",
        name: "Smart PDF Signer",
        description: "Sign PDF documents professionally. Select an area, draw your signature, and apply it to one or all pages instantly. 100% private, browser-based.",
        href: "/tools/pdf-signer",
        badge: "Free",
        icon: PenTool,
        tags: [
            "pdf", "sign", "signature", "esign", "contract", "initials",
            "sign pdf", "digital signature", "pdf signer", "fill and sign",
            "sign document", "e-signature", "sign pdf online", "pdf editor"
        ],
        accent: "#ffffff",
        category: "PDF",
    },
    {
        id: "image-compressor",
        name: "Image Compressor",
        description: "Compress JPEG, PNG & WebP images instantly in your browser. 100% private, no uploads needed.",
        href: "/tools/image-compressor",
        badge: "Free",
        icon: FileImage,
        tags: ["image", "compress", "jpeg", "png", "webp", "optimize", "resize"],
        accent: "#ffffff",
        category: "Images",
    },
    {
        id: "bg-remover",
        name: "Background Remover",
        description: "Remove backgrounds from your images instantly and for free. 100% private, processing happens in your browser.",
        href: "/tools/bg-remover",
        badge: "Free",
        icon: Eraser,
        tags: ["image", "background", "remover", "bg", "ai", "remove", "transparent", "creator"],
        accent: "#ffffff",
        category: "Images",
    },
    {
        id: "qr",
        name: "QR Code Generator",
        description: "Generate beautiful, customizable QR codes instantly. Download as PNG or SVG for free.",
        href: "/tools/qr",
        badge: "Free",
        icon: QrCode,
        tags: ["qr", "qrcode", "barcode", "link", "generate", "scan"],
        accent: "#ffffff",
        category: "Generate",
    },
    {
        id: "css-gradient",
        name: "CSS Gradient Maker",
        description: "Mix beautiful gradients and instantly copy the pure CSS. Real-time linear and radial controls with randomizer.",
        href: "/tools/css-gradient",
        badge: "Free",
        icon: Palette,
        tags: ["css", "gradient", "maker", "generator", "colors", "background", "design", "ui"],
        accent: "#ffffff",
        category: "Generate",
    },
    {
        id: "svg-patterns",
        name: "SVG Patterns",
        description: "A curated library of beautiful, seamless geometric SVG backgrounds ready to copy.",
        href: "/tools/svg-patterns",
        badge: "Free",
        icon: Shapes,
        tags: ["svg", "pattern", "background", "shapes", "geometric", "css", "data uri", "design"],
        accent: "#ffffff",
        category: "Generate",
    },
    {
        id: "icons",
        name: "Icon Library",
        description: "A beautifully clean icon library featuring premium outline icons. Click to copy the exact SVG or React component code.",
        href: "/tools/icons",
        badge: "Free",
        icon: Images,
        tags: ["icons", "svg", "lucide", "react", "components", "vector", "library", "assets"],
        accent: "#ffffff",
        category: "Generate",
    },
    {
        id: "e-signature",
        name: "E-Signature Creator",
        description: "Draw your signature smoothly online using your mouse or touch screen. Download instantly as a transparent PNG or SVG.",
        href: "/tools/e-signature",
        badge: "Free",
        icon: PenTool,
        tags: ["signature", "esign", "sign", "digital signature", "draw", "transparent", "png", "svg"],
        accent: "#ffffff",
        category: "Generate",
    },
    {
        id: "pomodoro",
        name: "Pomodoro Timer",
        description: "Boost your productivity with an animated focus timer, session tracking, and achievement system.",
        href: "/tools/pomodoro",
        badge: "Free",
        icon: Timer,
        tags: ["pomodoro", "timer", "focus", "productivity", "study", "work", "deep work", "break", "water reminder", "hydration", "drink water"],
        accent: "#ffffff",
        category: "Productivity",
    },
    {
        id: "typing-tester",
        name: "Typing Speed Tester",
        description: "Test and improve your typing speed and accuracy with real-time feedback and detailed stats.",
        href: "/tools/typing-tester",
        badge: "Free",
        icon: Keyboard,
        tags: ["typing", "speed", "test", "tester", "wpm", "accuracy", "practice", "keyboard", "typist"],
        accent: "#ffffff",
        category: "Productivity",
    },
    {
        id: "billing",
        name: "Smart Billing Tool",
        description: "Paperless billing for small merchants. Scan barcodes, add items, generate a customer QR receipt — no printing needed.",
        href: "/tools/billing",
        badge: "Free",
        icon: Receipt,
        tags: ["billing", "invoice", "gst", "receipt", "barcode", "qr", "merchant", "shop", "india", "retail", "pos"],
        accent: "#ffffff",
        category: "Business",
    },
    {
        id: "business-card",
        name: "Business Card Maker",
        description: "Design professional business cards online in minutes. Add your details, adjust colors, and export high-res PNGs.",
        href: "/tools/business-card",
        badge: "Free",
        icon: CreditCard,
        tags: ["business card", "maker", "generator", "design", "corporate", "card", "branding"],
        accent: "#ffffff",
        category: "Business",
    },
    {
        id: "image-converter",
        name: "Image Converter",
        description: "Convert JPG to PNG, PNG to WebP, or JPG to WebP instantly in your browser. Batch support, quality control, 100% private.",
        href: "/tools/image-converter",
        badge: "Free",
        icon: RefreshCw,
        tags: ["image", "convert", "jpg", "jpeg", "png", "webp", "format", "converter", "batch"],
        accent: "#ffffff",
        category: "Images",
    },
    {
        id: "ig-grid",
        name: "Instagram Grid Planner",
        description: "Plan your Instagram feed visually. Upload photos, drag and drop to rearrange, and see how your profile will look.",
        href: "/tools/ig-grid",
        badge: "Free",
        icon: Grid3X3,
        tags: ["instagram", "grid", "planner", "feed", "social", "media", "preview", "drag", "drop", "layout"],
        accent: "#ffffff",
        category: "Images",
    },
    {
        id: "image-cropper",
        name: "Advanced Image Cropper",
        description: "Crop images with precision. Set specific aspect ratios, custom dimensions, and download high quality results.",
        href: "/tools/image-cropper",
        badge: "Free",
        icon: Crop,
        tags: ["image", "crop", "cropper", "resize", "aspect", "ratio", "dimensions"],
        accent: "#ffffff",
        category: "Images",
    },
    {
        id: "image-to-text",
        name: "Image to Text",
        description: "Extract text from images using high-precision OCR. Convert screenshots, photos, and scanned documents into editable text instantly.",
        href: "/tools/image-to-text",
        badge: "Free",
        icon: FileText,
        tags: ["image", "ocr", "text", "extract", "scanner", "image to text", "photo to text"],
        accent: "#ffffff",
        category: "Images",
    },
    {
        id: "pdf-merger",
        name: "PDF Merger",
        description: "Merge and combine multiple PDF files into one document instantly. Upload PDFs, rearrange pages, and export — 100% private, runs in your browser.",
        href: "/tools/pdf-merger",
        badge: "Free",
        icon: Combine,
        tags: [
            "pdf", "merge", "combine", "join", "pdf merger", "merge pdfs",
            "combine pdfs", "join pdf", "merge pdf files", "pdf joiner",
            "merge pdf online", "combine pdf files", "document", "merge documents"
        ],
        accent: "#ffffff",
        category: "PDF",
    },
    {
        id: "pdf-compressor",
        name: "PDF Compressor",
        description: "Compress and reduce PDF file size instantly in your browser. Make your PDF smaller for email, sharing, or uploading — no uploads, 100% private.",
        href: "/tools/pdf-compressor",
        badge: "Free",
        icon: Minimize2,
        tags: [
            "pdf", "compress", "reduce", "size", "optimize", "shrink",
            "compress pdf", "reduce pdf size", "pdf compressor", "make pdf smaller",
            "pdf file size", "shrink pdf", "pdf optimizer", "smaller pdf",
            "compress pdf online", "pdf size reducer"
        ],
        accent: "#ffffff",
        category: "PDF",
    },
    {
        id: "pdf-splitter",
        name: "PDF Splitter",
        description: "Split a PDF into individual pages or extract specific page ranges. Visually select the pages you need and download them as a new PDF — free and private.",
        href: "/tools/pdf-splitter",
        badge: "Free",
        icon: Split,
        tags: [
            "pdf", "split", "extract", "pages", "separate", "cut",
            "split pdf", "pdf splitter", "extract pages", "pdf page extractor",
            "split pdf into pages", "separate pdf pages", "remove pages from pdf",
            "pdf cutter", "pdf page selector", "extract pdf pages"
        ],
        accent: "#ffffff",
        category: "PDF",
    },
    {
        id: "pdf-cropper",
        name: "PDF Cropper",
        description: "Visually crop and trim the margins or any region of your PDF pages. Set precise crop areas, apply to all pages, and export — 100% private, in-browser.",
        href: "/tools/pdf-cropper",
        badge: "Free",
        icon: Crop,
        tags: [
            "pdf", "crop", "trim", "margins", "cropper", "cut",
            "crop pdf", "pdf cropper", "trim pdf", "pdf margin trimmer",
            "crop pdf pages", "remove margins pdf", "pdf crop tool",
            "trim pdf margins", "crop pdf online", "pdf viewport"
        ],
        accent: "#ffffff",
        category: "PDF",
    },
    {
        id: "pdf-text-extractor",
        name: "PDF Text Extractor",
        description: "Instantly extract paragraphs and raw text from any PDF into an editable Word Document (DOCX). Perfect for essays and text files. Processed locally for 100% privacy.",
        href: "/tools/pdf-text-extractor",
        badge: "Free",
        icon: FileText,
        tags: [
            "pdf", "word", "docx", "convert", "extract", "text",
            "pdf to word", "pdf to docx", "convert pdf", "pdf to document",
            "free pdf text extractor", "pdf converter", "pdf text extractor"
        ],
        accent: "#ffffff",
        category: "PDF",
    },
    {
        id: "notes",
        name: "Smart Notes",
        description: "A beautiful, versatile workspace for capturing thoughts, drafting articles, and organizing your notes securely in your browser.",
        href: "/tools/notes",
        badge: "Free",
        icon: NotebookPen,
        tags: ["notes", "workspace", "editor", "markdown", "write", "draft", "document", "text"],
        accent: "#ffffff",
        category: "Productivity",
    },
    {
        id: "kanban",
        name: "Kanban Board",
        description: "A professional, minimalist Kanban board with seamless drag-and-drop. Organize tasks, track project status, and boost your workflow privately.",
        href: "/tools/kanban",
        badge: "Free",
        icon: KanbanSquare,
        tags: ["kanban", "board", "task", "project", "management", "workflow", " productivity", "organization", "dnd"],
        accent: "#ffffff",
        category: "Productivity",
    },
    {
        id: "image-to-pdf",
        name: "Image to PDF",
        description: "Convert JPG, PNG, and WebP images into a single PDF instantly. Drag to reorder, set page size, margin and quality — 100% private, in your browser.",
        href: "/tools/image-to-pdf",
        badge: "Free",
        icon: ImagePlus,
        tags: [
            "image", "jpg", "png", "webp", "gif", "photo", "picture",
            "image to pdf", "jpg to pdf", "png to pdf", "photos to pdf",
            "convert image to pdf", "picture to pdf", "convert jpg to pdf",
            "images to pdf", "photo to pdf", "webp to pdf", "pdf from images"
        ],
        accent: "#ffffff",
        category: "PDF",
    },
    {
        id: "game-2048",
        name: "2048 Game",
        description: "The classic sliding tile puzzle. Swipe to merge numbers and reach the 2048 tile in this addictive, brain-teasing game.",
        href: "/tools/2048",
        badge: "Free",
        icon: Hash,
        tags: ["game", "puzzle", "2048", "logic", "sliding", "numbers", "brain", "fun"],
        accent: "#ffffff",
        category: "Games",
    },
    {
        id: "game-sudoku",
        name: "Sudoku Pro",
        description: "Sharpen your mind with daily Sudoku. Multiple difficulty levels, clean interface, and real-time error checking.",
        href: "/tools/sudoku",
        badge: "Free",
        icon: Table,
        tags: ["game", "sudoku", "logic", "puzzle", "numbers", "brain", "intelligence"],
        accent: "#ffffff",
        category: "Games",
    },
    {
        id: "game-wordle",
        name: "Wordle Clone",
        description: "Guess the hidden 5-letter word in 6 tries. A daily viral word game to challenge your vocabulary.",
        href: "/tools/wordle",
        badge: "Free",
        icon: WholeWord,
        tags: ["game", "wordle", "word", "puzzle", "vocabulary", "daily", "guess"],
        accent: "#ffffff",
        category: "Games",
    },
    {
        id: "game-dino",
        name: "Dino Run",
        description: "An infinite runner adventure. Jump over obstacles, survive as long as possible, and set new high scores.",
        href: "/tools/dino",
        badge: "Free",
        icon: Gamepad2,
        tags: ["game", "dino", "runner", "infinite", "arcade", "avoid", "jump", "pixel"],
        accent: "#ffffff",
        category: "Games",
    },
    {
        id: "game-math",
        name: "Quick Math",
        description: "Test your mental arithmetic speed. Solve as many math problems as possible in 60 seconds and climb the ranks.",
        href: "/tools/math",
        badge: "Free",
        icon: Calculator,
        tags: ["game", "math", "arithmetic", "speed", "test", "brain", "training", "logic"],
        accent: "#ffffff",
        category: "Games",
    },
    {
        id: "game-chess",
        name: "Grandmaster Chess",
        description: "Play against a powerful Computer Engine or challenge yourself. Analyze moves, practice openings, and sharpen your tactical vision on a clean, ad-free board.",
        href: "/tools/chess",
        badge: "Free",
        icon: Crown,
        tags: ["game", "chess", "strategy", "board", "engine", "tactics", "logic", "puzzle", "grandmaster"],
        accent: "#ffffff",
        category: "Games",
    },
    {
        id: "ui-pixel-perfect",
        name: "Pixel Perfect",
        description: "Develop a precise eye for pixels. Draw boxes matching exact dimension targets to train your UI spatial awareness.",
        href: "/tools/pixel-perfect",
        badge: "Free",
        icon: ScanLine,
        tags: ["ui", "training", "pixels", "design", "box"],
        accent: "from-blue-500/20 to-cyan-500/20",
        category: "Design Training"
    },
    {
        id: "ui-is-it-centered",
        name: "Is It Centered",
        description: "Sharpen your spacing discernment. Identify whether a geometric dot is perfectly centered within a container.",
        href: "/tools/is-it-centered",
        badge: "Free",
        icon: CropIcon,
        tags: ["ui", "training", "alignment", "design", "center"],
        accent: "from-fuchsia-500/20 to-pink-500/20",
        category: "Design Training"
    },
    {
        id: "pdf-unlocker",
        name: "PDF Password Remover",
        description: "Instantly remove passwords from your PDF files. Unlock encrypted PDFs locally in your browser without uploading to any server for 100% privacy.",
        href: "/tools/pdf-unlocker",
        badge: "Free",
        icon: Unlock,
        tags: ["pdf", "unlock", "password", "remove", "decrypt", "security", "unprotect", "pdf password remover"],
        accent: "#ffffff",
        category: "PDF"
    }
];
